name: OpenID Connect
on: push
env: #AWSの認証アクションへ指定する入力パラメータを環境変数として定義
  ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
  SESSION_NAME: gh-oidc-${{ github.run_id }}-${{ github.run_attempt }}
jobs: #AWSの認証アクション
  connect:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write #OIDCトークンの取得を許可
    steps:
      - uses: aws-actions/configure-aws-credentials@v4 #AWSの認証アクション
        with:
          role-to-assume: ${{ env.ROLE_ARN }} #IAMロールARN
          role-session-name: ${{ env.SESSION_NAME }} #セッション名
          aws-region: ap-northeast-1 #デフォルトリージョン
      - run: aws iam list-users #参照系API
      - run: aws iam create-user --user-name invalid || true #参照系API(IAMReadOnlyAccessにより失敗)
